### ISSUE TITLE
git hub とslackを連帯させてみよう

### ISSUE THREAD

**Issue by akiya3** [ry0t4/CoordinateBook#7]
slackのチャンネルは私と普段やり取りしているものとは別の部屋を作成しましょう
私と校長と北澤さんを招待しておいてください
リポジトリ名-githubあたりの部屋名でいいと思います

slackの左側のリストの一番下からAppの+を押して追加します
`GitHub Notifications`
を追加したら
![2018-05-19 1 52 29](https://user-images.githubusercontent.com/20620515/40247456-6b14dcca-5b07-11e8-89b6-3856cfdf1d9e.png)
の様に設定しておきましょう

**Comment by ry0t4** [comment]
Appの追加と設定が完了しました！
